// Guest-native public CFNetwork string constants. Values are taken
// from Apple's iOS 10.3 CFNetwork image to preserve its legacy ABI.

#import <CFNetwork/CFNetwork.h>

#define LC32_CFNETWORK_STRING(name, value) \
    const CFStringRef name = CFSTR(value)

LC32_CFNETWORK_STRING(kCFDNSServiceFailureKey, "kCFDNSServiceFailureKey");
LC32_CFNETWORK_STRING(kCFErrorDomainWinSock, "kCFErrorDomainWinSock");
LC32_CFNETWORK_STRING(kCFFTPResourceGroup, "kCFFTPResourceGroup");
LC32_CFNETWORK_STRING(kCFFTPResourceLink, "kCFFTPResourceLink");
LC32_CFNETWORK_STRING(kCFFTPResourceModDate, "kCFFTPResourceModDate");
LC32_CFNETWORK_STRING(kCFFTPResourceMode, "kCFFTPResourceMode");
LC32_CFNETWORK_STRING(kCFFTPResourceName, "kCFFTPResourceName");
LC32_CFNETWORK_STRING(kCFFTPResourceOwner, "kCFFTPResourceOwner");
LC32_CFNETWORK_STRING(kCFFTPResourceSize, "kCFFTPResourceSize");
LC32_CFNETWORK_STRING(kCFFTPResourceType, "kCFFTPResourceType");
LC32_CFNETWORK_STRING(kCFFTPStatusCodeKey, "kCFFTPStatusCodeKey");
LC32_CFNETWORK_STRING(kCFGetAddrInfoFailureKey, "kCFGetAddrInfoFailureKey");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationAccountDomain, "kCFHTTPAuthenticationAccountDomain");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationPassword, "kCFHTTPAuthenticationPassword");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeBasic, "Basic");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeDigest, "Digest");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeNTLM, "NTLM");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeNegotiate, "Negotiate");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeNegotiate2, "Nego2");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationSchemeXMobileMeAuthToken, "X-MobileMe-AuthToken");
LC32_CFNETWORK_STRING(kCFHTTPAuthenticationUsername, "kCFHTTPAuthenticationUsername");
LC32_CFNETWORK_STRING(kCFHTTPVersion2_0, "HTTP/2.0");
LC32_CFNETWORK_STRING(kCFNetworkProxiesHTTPEnable, "HTTPEnable");
LC32_CFNETWORK_STRING(kCFNetworkProxiesHTTPPort, "HTTPPort");
LC32_CFNETWORK_STRING(kCFNetworkProxiesHTTPProxy, "HTTPProxy");
LC32_CFNETWORK_STRING(kCFNetworkProxiesProxyAutoConfigEnable, "ProxyAutoConfigEnable");
LC32_CFNETWORK_STRING(kCFNetworkProxiesProxyAutoConfigURLString, "ProxyAutoConfigURLString");
LC32_CFNETWORK_STRING(kCFProxyAutoConfigurationJavaScriptKey, "kCFProxyAutoConfigurationJavaScriptKey");
LC32_CFNETWORK_STRING(kCFProxyAutoConfigurationURLKey, "kCFProxyAutoConfigurationURLKey");
LC32_CFNETWORK_STRING(kCFProxyPasswordKey, "kCFProxyPasswordKey");
LC32_CFNETWORK_STRING(kCFProxyTypeAutoConfigurationJavaScript, "kCFProxyTypeAutoConfigurationJavaScript");
LC32_CFNETWORK_STRING(kCFProxyTypeAutoConfigurationURL, "kCFProxyTypeAutoConfigurationURL");
LC32_CFNETWORK_STRING(kCFProxyTypeFTP, "kCFProxyTypeFTP");
LC32_CFNETWORK_STRING(kCFProxyTypeHTTP, "kCFProxyTypeHTTP");
LC32_CFNETWORK_STRING(kCFProxyTypeHTTPS, "kCFProxyTypeHTTPS");
LC32_CFNETWORK_STRING(kCFProxyTypeKey, "kCFProxyTypeKey");
LC32_CFNETWORK_STRING(kCFProxyTypeNone, "kCFProxyTypeNone");
LC32_CFNETWORK_STRING(kCFProxyTypeSOCKS, "kCFProxyTypeSOCKS");
LC32_CFNETWORK_STRING(kCFProxyUsernameKey, "kCFProxyUsernameKey");
LC32_CFNETWORK_STRING(kCFSOCKSNegotiationMethodKey, "kCFSOCKSNegotiationMethodKey");
LC32_CFNETWORK_STRING(kCFSOCKSStatusCodeKey, "kCFSOCKSStatusCodeKey");
LC32_CFNETWORK_STRING(kCFSOCKSVersionKey, "kCFSOCKSVersionKey");
LC32_CFNETWORK_STRING(kCFStreamNetworkServiceTypeBackground, "kCFStreamNetworkServiceTypeBackground");
LC32_CFNETWORK_STRING(kCFStreamNetworkServiceTypeCallSignaling, "kCFStreamNetworkServiceTypeCallSignaling");
LC32_CFNETWORK_STRING(kCFStreamNetworkServiceTypeVideo, "kCFStreamNetworkServiceTypeVideo");
LC32_CFNETWORK_STRING(kCFStreamNetworkServiceTypeVoice, "kCFStreamNetworkServiceTypeVoice");
LC32_CFNETWORK_STRING(kCFStreamPropertyConnectionIsCellular, "kCFStreamPropertyConnectionIsCellular");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPAttemptPersistentConnection, "kCFStreamPropertyFTPAttemptPersistentConnection");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPFetchResourceInfo, "kCFStreamPropertyFTPFetchResourceInfo");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPFileTransferOffset, "kCFStreamPropertyFTPFileTransferOffset");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPPassword, "kCFStreamPropertyFTPPassword");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPProxy, "kCFStreamPropertyFTPProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPProxyHost, "FTPProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPProxyPassword, "kCFStreamPropertyFTPProxyPassword");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPProxyPort, "FTPPort");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPProxyUser, "kCFStreamPropertyFTPProxyUser");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPResourceSize, "kCFStreamPropertyFTPResourceSize");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPUsePassiveMode, "kCFStreamPropertyFTPUsePassiveMode");
LC32_CFNETWORK_STRING(kCFStreamPropertyFTPUserName, "kCFStreamPropertyFTPUserName");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPAttemptPersistentConnection, "kCFStreamPropertyHTTPAttemptPersistentConnection");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPFinalRequest, "kCFStreamPropertyHTTPFinalRequest");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPFinalURL, "kCFStreamPropertyHTTPFinalURL");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPProxyHost, "HTTPProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPProxyPort, "HTTPPort");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPRequestBytesWrittenCount, "kCFStreamPropertyHTTPRequestBytesWrittenCount");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPSProxyHost, "HTTPSProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertyHTTPSProxyPort, "HTTPSPort");
LC32_CFNETWORK_STRING(kCFStreamPropertyNoCellular, "kCFStreamPropertyNoCellular");
LC32_CFNETWORK_STRING(kCFStreamPropertyProxyLocalBypass, "ExcludeSimpleHostnames");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSPassword, "kCFStreamPropertySOCKSPassword");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSProxy, "kCFStreamPropertySOCKSProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSProxyHost, "SOCKSProxy");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSProxyPort, "SOCKSPort");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSUser, "kCFStreamPropertySOCKSUser");
LC32_CFNETWORK_STRING(kCFStreamPropertySOCKSVersion, "kCFStreamPropertySOCKSVersion");
LC32_CFNETWORK_STRING(kCFStreamPropertySSLContext, "kCFStreamPropertySSLContext");
LC32_CFNETWORK_STRING(kCFStreamPropertySSLPeerCertificates, "kCFStreamPropertySSLPeerCertificates");
LC32_CFNETWORK_STRING(kCFStreamPropertySSLPeerTrust, "kCFStreamPropertySSLPeerTrust");
LC32_CFNETWORK_STRING(kCFStreamPropertyShouldCloseNativeSocket, "kCFStreamPropertyShouldCloseNativeSocket");
LC32_CFNETWORK_STRING(kCFStreamPropertySocketExtendedBackgroundIdleMode, "kCFStreamPropertySocketExtendedBackgroundIdleMode");
LC32_CFNETWORK_STRING(kCFStreamPropertySocketRemoteHost, "kCFStreamPropertySocketRemoteHost");
LC32_CFNETWORK_STRING(kCFStreamPropertySocketRemoteNetService, "kCFStreamPropertySocketRemoteNetService");
LC32_CFNETWORK_STRING(kCFStreamPropertySocketSecurityLevel, "kCFStreamPropertySocketSecurityLevel");
LC32_CFNETWORK_STRING(kCFStreamSocketSOCKSVersion4, "kCFStreamSocketSOCKSVersion4");
LC32_CFNETWORK_STRING(kCFStreamSocketSOCKSVersion5, "kCFStreamSocketSOCKSVersion5");
LC32_CFNETWORK_STRING(kCFStreamSocketSecurityLevelNegotiatedSSL, "kCFStreamSocketSecurityLevelNegotiatedSSL");
LC32_CFNETWORK_STRING(kCFStreamSocketSecurityLevelNone, "kCFStreamSocketSecurityLevelNone");
LC32_CFNETWORK_STRING(kCFStreamSocketSecurityLevelSSLv2, "kCFStreamSocketSecurityLevelSSLv2");
LC32_CFNETWORK_STRING(kCFStreamSocketSecurityLevelSSLv3, "kCFStreamSocketSecurityLevelSSLv3");
LC32_CFNETWORK_STRING(kCFStreamSocketSecurityLevelTLSv1, "kCFStreamSocketSecurityLevelTLSv1");
LC32_CFNETWORK_STRING(kCFURLErrorFailingURLErrorKey, "NSErrorFailingURLKey");
LC32_CFNETWORK_STRING(kCFURLErrorFailingURLStringErrorKey, "NSErrorFailingURLStringKey");

#undef LC32_CFNETWORK_STRING
